# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EthosLabs.us
description: > # this means to ignore newlines until "baseurl:"
  This is Phantom, a simple design built around a grid of large, colorful, semi-interactive
  image tiles (of which you can have as many or as few as you like). Makes use of some
  SVG and animation techniques I've been experimenting with on that other project of mine
  you may have heard about (https://carrd.co), and includes a handy generic page for whatever.
url: "http://ethoslabs.us" # the base hostname & protocol for your site

# Contact settings
email: hello@ethoslabs.us
twitter_username: abhinemani
github_username:  abhinemani

# Build settings
markdowm: kramdown

kramdown:
  input:      GFM
  auto_ids:   false

exclude: ["README.md", "LICENSE.md", "screenshot.png"]
