# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EthosLabs.us
description: > # this means to ignore newlines until "baseurl:"
  Good government in the 21st century means good technology. But often it seems too hard for new startups to get into the business of government, even though innovative public servants and entrepreneurs want to work together. That's where EthosLabs comes in.
url: "http://ethoslabs.us" # the base hostname & protocol for your site

# Contact settings
email: hello@ethoslabs.us
twitter_username: abhinemani
github_username:  abhinemani

# Build settings
markdowm: kramdown

kramdown:
  input:      GFM
  auto_ids:   false

exclude: ["README.md", "LICENSE.md", "screenshot.png"]
